#!/bin/bash

PATH='/bin:/sbin:/usr/bin:/usr/sbin'

APT_OPTS='-q -q -y'
POSTGRESQL_VERSION='9.1'
PUPPET_REPO='http://apt.puppetlabs.com/'
DISTRIB_CODENAME=`awk -F= '/^DISTRIB_CODENAME/ { print $2 }' /etc/lsb-release`

# Find puppetmaster
echo "search ryanleary.org" >> /etc/resolv.conf

# Make apt-get install really quiet.
export DEBIAN_FRONTEND=noninteractive

if [ "`/usr/bin/id -u`" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

function add_puppet_repository()
{
  echo "deb ${PUPPET_REPO} ${DISTRIB_CODENAME} main dependencies" > /etc/apt/sources.list.d/puppet.list
  curl --silent ${PUPPET_REPO}/pubkey.gpg | apt-key add - > /dev/null
  apt-get ${APT_OPTS} update
}

function install_puppet()
{
  apt-get ${APT_OPTS} update
  apt-get ${APT_OPTS} install puppet
  cat > /etc/default/puppet << EOF
# Defaults for puppet - sourced by /etc/init.d/puppet
START=yes
DAEMON_OPTS=""
EOF
  /etc/init.d/puppet start
}

add_puppet_repository
install_puppet
